// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-arm64.zst
var embeddedUpgradeShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "4cb3c0d0b7725414fa4aebdd4542660bde2537bf0c2814eb54783c81c276a1bd",
		SHA256:       "bbfdea4a172584829e912db48ddac33a2549ef560803a130cce8e28c0f2b64bc",
		Zstd:         embeddedUpgradeShim_linux_arm64,
	})
}
