// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-windows-amd64.zst
var embeddedUpgradeShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "4cb3c0d0b7725414fa4aebdd4542660bde2537bf0c2814eb54783c81c276a1bd",
		SHA256:       "31ab2061e721c57d6e890e1a287137280a2228ba47dc4d17630f26f65f797732",
		Zstd:         embeddedUpgradeShim_windows_amd64,
	})
}
