// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "4cb3c0d0b7725414fa4aebdd4542660bde2537bf0c2814eb54783c81c276a1bd",
		SHA256:       "f3d1a54d894990a1aeb3a393f66b1d6b62eca2c8bedd600e0906804f317f6808",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
