// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-amd64.zst
var embeddedUpgradeShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "4cb3c0d0b7725414fa4aebdd4542660bde2537bf0c2814eb54783c81c276a1bd",
		SHA256:       "90fa2e9cc553b4a1b50a9d275c446f918e1d6a75d623d71a31ee5f6df9befa43",
		Zstd:         embeddedUpgradeShim_darwin_amd64,
	})
}
