// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-linux-amd64.zst
var embeddedUpgradeShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "4cb3c0d0b7725414fa4aebdd4542660bde2537bf0c2814eb54783c81c276a1bd",
		SHA256:       "805b746c114e0c3d599d2094d092566d2ec19799936cd74de6872f777fc8cf75",
		Zstd:         embeddedUpgradeShim_linux_amd64,
	})
}
