// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "80de6a4c48d3564b2e19787f07ddeb683f35654211b9ba41e1a71a8914d20f00",
		SHA256:       "2c3af632c2ac46568915cd65ad2ea01c2596e4bb3d23db845c861fce01785cc9",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
